const DRIVE='https://www.googleapis.com/drive/v3';
export const defaultSchoolData=()=>({schemaVersion:1,revision:0,students:[],cases:[],teachers:[],settings:{school:'',code:'',address:'',signatory:'Guru Besar',logo:''},onboarding:{driveConnected:false,profileCompleted:false,completed:false}});
export class DriveStore {
 constructor({registry,clientId,clientSecret,fetcher=fetch}){this.registry=registry;this.clientId=clientId;this.clientSecret=clientSecret;this.fetch=fetcher;this.tokens=new Map();}
 async accessToken(school){const cached=this.tokens.get(school.id);if(cached&&cached.expires>Date.now())return cached.value;if(!school.encrypted_token){const e=Error('Pentadbir sekolah perlu pautkan Google Drive terlebih dahulu.');e.status=424;throw e;}
 const response=await this.fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'refresh_token',refresh_token:this.registry.decrypt(school.encrypted_token),client_id:this.clientId,client_secret:this.clientSecret}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok||!result.access_token){const e=Error('Kebenaran Drive telah tamat atau ditarik. Pentadbir perlu pautkan semula Drive sekolah.');e.status=424;throw e;}this.tokens.set(school.id,{value:result.access_token,expires:Date.now()+Math.max(0,(result.expires_in||3600)-60)*1000});return result.access_token;
 }
 async request(school,url,options={}){const token=await this.accessToken(school);const response=await this.fetch(url,{...options,headers:{...options.headers,Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(15000)});if(!response.ok){if(response.status===401)this.tokens.delete(school.id);const e=Error(response.status===403?'Google Drive tidak membenarkan operasi ini. Semak kebenaran dan kuota sekolah.':'Operasi Google Drive gagal. Data tidak dianggap berjaya disimpan.');e.status=response.status===404?424:502;throw e;}return response;}
 async provision(school){return this.registry.locked(school.id,async()=>{
  let current=this.registry.db.prepare('SELECT * FROM schools WHERE id=?').get(school.id);if(!current)throw Error('Sekolah tidak ditemui.');if(!current.code||!current.name)throw Error('Lengkapkan kod dan nama sekolah dahulu.');
  if(!current.folder_id){const q=`trashed=false and mimeType='application/vnd.google-apps.folder' and appProperties has { key='tegasTenant' and value='${current.id}' }`;const result=await(await this.request(current,`${DRIVE}/files?`+new URLSearchParams({q,fields:'files(id)'}))).json();if(result.files?.length>1)throw Error('Terdapat folder sekolah berulang. Semak folder sebelum meneruskan.');if(result.files?.[0]){this.registry.bindFolder(current.id,result.files[0].id);current={...current,folder_id:result.files[0].id};}}
  if(!current.folder_id){const response=await this.request(current,`${DRIVE}/files?fields=id`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:`tegas(${current.code})`,mimeType:'application/vnd.google-apps.folder',appProperties:{tegasTenant:current.id}})});const {id}=await response.json();if(!id)throw Error('Folder Drive tidak dapat disahkan.');this.registry.bindFolder(current.id,id);current={...current,folder_id:id};}
  if(!current.file_id){const q=`trashed=false and '${current.folder_id}' in parents and name='tegas-school-data.json' and appProperties has { key='tegasTenant' and value='${current.id}' }`;const result=await(await this.request(current,`${DRIVE}/files?`+new URLSearchParams({q,fields:'files(id)'}))).json();if(result.files?.length>1)throw Error('Terdapat fail sekolah berulang. Semak fail sebelum meneruskan.');if(result.files?.[0]){this.registry.bindFile(current.id,result.files[0].id);current={...current,file_id:result.files[0].id};}}
  if(!current.file_id){const metadata={name:'tegas-school-data.json',mimeType:'application/json',parents:[current.folder_id],appProperties:{tegasTenant:current.id}};const data=defaultSchoolData();data.settings.school=current.name;data.settings.code=current.code;data.onboarding={driveConnected:true,profileCompleted:true,completed:false};const boundary='tegas'+crypto.randomUUID();const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(data)}\r\n--${boundary}--`;
   const response=await this.request(current,'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});const {id}=await response.json();if(!id)throw Error('Fail data Drive tidak dapat disahkan.');this.registry.bindFile(current.id,id);current={...current,file_id:id};}
  await this.read(current);return current;
 });}
 async read(school){if(!school.file_id)return defaultSchoolData();const metadata=await(await this.request(school,`${DRIVE}/files/${encodeURIComponent(school.file_id)}?fields=id,appProperties,trashed`)).json();if(metadata.trashed||metadata.appProperties?.tegasTenant!==school.id)throw Error('Fail Drive tidak sepadan dengan sekolah yang dibenarkan.');const data=await(await this.request(school,`${DRIVE}/files/${encodeURIComponent(school.file_id)}?alt=media`)).json();if(data.schemaVersion!==1||!Array.isArray(data.students)||!Array.isArray(data.cases)||!data.settings||!Number.isSafeInteger(data.revision))throw Error('Format data Drive tidak sah. Pulihkan backup sebelum meneruskan.');data.teachers??=[];return data;}
 async mutate(school,expectedRevision,fn,{backup=false}={}){if(!school.file_id){const e=Error('Pautkan Drive sekolah terlebih dahulu.');e.status=424;throw e;}return this.registry.locked(school.id,async()=>{
  const data=await this.read(school);if(String(data.revision)!==String(expectedRevision)){const e=Error('Data telah berubah. Refresh dahulu supaya perubahan guru lain tidak ditindih.');e.status=409;throw e;}
  const result=await fn(data);if(backup)await this.request(school,`${DRIVE}/files/${encodeURIComponent(school.file_id)}/copy?fields=id`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:`backup-before-replace-${new Date().toISOString()}.json`,parents:[school.folder_id],appProperties:{tegasTenant:school.id}})});data.revision++;data.updatedAt=new Date().toISOString();await this.request(school,`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(school.file_id)}?uploadType=media&fields=id`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return {...result,revision:data.revision};
 });}
}
