import {DatabaseSync} from 'node:sqlite';
import {createCipheriv,createDecipheriv,randomBytes,randomUUID,scryptSync,timingSafeEqual} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import session from 'express-session';
export class Registry {
 constructor(directory,key){mkdirSync(directory,{recursive:true});this.key=Buffer.from(key||'','base64');if(this.key.length!==32)throw Error('TOKEN_ENCRYPTION_KEY mesti 32 bait dalam base64.');this.db=new DatabaseSync(`${directory}/saas-registry.sqlite`);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=1000;
 CREATE TABLE IF NOT EXISTS schools(id TEXT PRIMARY KEY, owner_sub TEXT UNIQUE NOT NULL, name TEXT, code TEXT UNIQUE, ready INTEGER NOT NULL DEFAULT 0,pin_salt TEXT,pin_hash TEXT,pin_version INTEGER NOT NULL DEFAULT 0, folder_id TEXT, file_id TEXT, encrypted_token TEXT);
 CREATE TABLE IF NOT EXISTS members(tenant_id TEXT NOT NULL,email TEXT UNIQUE NOT NULL,role TEXT NOT NULL,PRIMARY KEY(tenant_id,email));
 CREATE TABLE IF NOT EXISTS sessions(sid TEXT PRIMARY KEY,payload TEXT NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS access_attempts(id TEXT PRIMARY KEY,attempts INTEGER NOT NULL,started INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS locks(tenant_id TEXT PRIMARY KEY,holder TEXT NOT NULL,expires INTEGER NOT NULL);`);}
 setProfile(tenantId,code,name,pin){const normalized=String(code||'').trim().toUpperCase();if(!/^[A-Z0-9]{4,20}$/.test(normalized)||!String(name||'').trim())throw Error('Masukkan kod sekolah (4–20 huruf/angka) dan nama sekolah.');const duplicate=this.db.prepare('SELECT id FROM schools WHERE code=? AND id<>?').get(normalized,tenantId);if(duplicate){const e=Error('Kod sekolah sudah didaftarkan. Gunakan URL sekolah dan minta pentadbir memberikan akses.');e.status=409;throw e;}if(!/^\d{4}$/.test(String(pin||'')))throw Error('Tetapkan kod akses 4 angka.');this.db.prepare('UPDATE schools SET code=?,name=? WHERE id=?').run(normalized,String(name).trim().slice(0,1000),tenantId);this.setPin(tenantId,pin);return this.db.prepare('SELECT * FROM schools WHERE id=?').get(tenantId);}
 setPin(tenantId,pin){if(!/^\d{4}$/.test(String(pin||'')))throw Error('Kod akses mesti tepat 4 angka.');const salt=randomBytes(16).toString('base64');const hash=scryptSync(pin,Buffer.from(salt,'base64'),32).toString('base64');this.db.prepare('UPDATE schools SET pin_salt=?,pin_hash=?,pin_version=pin_version+1 WHERE id=?').run(salt,hash,tenantId);this.db.prepare('DELETE FROM access_attempts WHERE id LIKE ?').run(tenantId+':%');}
 verifyPin(school,userSub,pin){const key=school.id+':'+userSub,globalKey=school.id+':global',now=Date.now(),window=15*60000;const global=this.db.prepare('SELECT * FROM access_attempts WHERE id=?').get(globalKey);if(global&&global.started+window<=now)this.db.prepare('DELETE FROM access_attempts WHERE id=?').run(globalKey);else if(global?.attempts>=30){const e=Error('Akses sekolah disekat sementara kerana terlalu banyak cubaan. Cuba selepas 15 minit.');e.status=429;throw e;}let attempt=this.db.prepare('SELECT * FROM access_attempts WHERE id=?').get(key);if(attempt&&attempt.started+window<=now){this.db.prepare('DELETE FROM access_attempts WHERE id=?').run(key);attempt=null;}if(attempt?.attempts>=5){const e=Error('Terlalu banyak cubaan kod. Cuba semula selepas 15 minit.');e.status=429;throw e;}const candidate=/^\d{4}$/.test(String(pin||''))&&school.pin_salt?scryptSync(pin,Buffer.from(school.pin_salt,'base64'),32):Buffer.alloc(32);const correct=school.pin_hash&&timingSafeEqual(candidate,Buffer.from(school.pin_hash,'base64'));if(!correct){this.db.prepare('INSERT INTO access_attempts VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET attempts=attempts+1').run(key,1,now);this.db.prepare('INSERT INTO access_attempts VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET attempts=attempts+1').run(globalKey,1,now);const e=Error('Kod akses sekolah tidak sah.');e.status=403;throw e;}this.db.prepare('DELETE FROM access_attempts WHERE id=?').run(key);return true;}
 setReady(tenantId){this.db.prepare('UPDATE schools SET ready=1 WHERE id=?').run(tenantId);}
 schoolByCode(code){return this.db.prepare('SELECT * FROM schools WHERE code=?').get(String(code||'').toUpperCase());}
 byCode(code){return this.db.prepare('SELECT id,code,name,ready FROM schools WHERE code=?').get(String(code||'').toUpperCase());}
 encrypt(value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key,iv);const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(x=>x.toString('base64')).join('.');}
 decrypt(value){const [iv,tag,data]=value.split('.').map(x=>Buffer.from(x,'base64'));const cipher=createDecipheriv('aes-256-gcm',this.key,iv);cipher.setAuthTag(tag);return Buffer.concat([cipher.update(data),cipher.final()]).toString('utf8');}
 schoolFor(user){return this.db.prepare('SELECT s.*,m.role FROM schools s JOIN members m ON s.id=m.tenant_id WHERE m.email=?').get(user.email.toLowerCase());}
 enroll(user){const bound=this.schoolFor(user);if(bound)return bound;const owned=this.db.prepare('SELECT * FROM schools WHERE owner_sub=?').get(user.sub);const id=owned?.id||randomUUID();this.db.exec('BEGIN');try{if(!owned)this.db.prepare('INSERT INTO schools(id,owner_sub,name) VALUES(?,?,?)').run(id,user.sub,'Sekolah baharu');this.db.prepare('INSERT INTO members VALUES(?,?,?)').run(id,user.email.toLowerCase(),'admin');this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}return this.schoolFor(user);}
 bindToken(tenantId,token){this.db.prepare('UPDATE schools SET encrypted_token=? WHERE id=?').run(this.encrypt(token),tenantId);}
 bindFolder(tenantId,folderId){this.db.prepare('UPDATE schools SET folder_id=? WHERE id=?').run(folderId,tenantId);}
 bindFile(tenantId,fileId){this.db.prepare('UPDATE schools SET file_id=? WHERE id=?').run(fileId,tenantId);}
 renameSchool(tenantId,name){this.db.prepare('UPDATE schools SET name=? WHERE id=?').run(name,tenantId);}
 async locked(tenantId,fn){const holder=randomUUID(),now=Date.now();const result=this.db.prepare('INSERT INTO locks VALUES(?,?,?) ON CONFLICT(tenant_id) DO UPDATE SET holder=excluded.holder,expires=excluded.expires WHERE locks.expires<?').run(tenantId,holder,now+180000,now);if(!result.changes){const e=Error('Data sekolah sedang disimpan oleh guru lain. Cuba semula selepas refresh.');e.status=409;throw e;}try{return await fn();}finally{this.db.prepare('DELETE FROM locks WHERE tenant_id=? AND holder=?').run(tenantId,holder);}}
 close(){this.db.close();}
}
export class SqliteSessionStore extends session.Store {
 constructor(registry){super();this.db=registry.db;}
 get(sid,cb){try{const row=this.db.prepare('SELECT payload FROM sessions WHERE sid=? AND expires>?').get(sid,Date.now());cb(null,row?JSON.parse(row.payload):null);}catch(e){cb(e);}}
 set(sid,value,cb=()=>{}){try{this.db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());this.db.prepare('INSERT INTO sessions VALUES(?,?,?) ON CONFLICT(sid) DO UPDATE SET payload=excluded.payload,expires=excluded.expires').run(sid,JSON.stringify(value),value.cookie?.expires?new Date(value.cookie.expires).getTime():Date.now()+8*3600000);cb();}catch(e){cb(e);}}
 destroy(sid,cb=()=>{}){try{this.db.prepare('DELETE FROM sessions WHERE sid=?').run(sid);cb();}catch(e){cb(e);}}
 touch(sid,value,cb){this.set(sid,value,cb);}
}
