import React,{useState} from 'react';
import {ShieldCheck,GraduationCap,FolderCheck,Upload,Link,CheckCircle2,ArrowRight,Copy,AlertCircle} from 'lucide-react';
export default function Onboarding({data,user,demo,api,onRefresh,onImport,busy,run}){
 const [school,setSchool]=useState(data.settings.school||''),[code,setCode]=useState(data.settings.code||''),[pin,setPin]=useState(''),[profileSaved,setProfileSaved]=useState(data.onboarding.profileCompleted),[folderBusy,setFolderBusy]=useState(false),[doneUrl,setDoneUrl]=useState(''),[copied,setCopied]=useState(false),[error,setError]=useState('');
 const connected=data.onboarding.driveConnected;const step=doneUrl?4:connected?3:profileSaved?2:1;
 const perform=async fn=>{setError('');try{await fn();}catch(e){setError(e.message);}};
 const provision=async()=>{setFolderBusy(true);try{await api('onboarding/provision',{});await onRefresh();}finally{setFolderBusy(false);}};
 const saveProfile=()=>perform(async()=>{await api('onboarding/profile',{school,code,pin});setProfileSaved(true);setPin('');await provision();});
 if(data.role&&data.role!=='admin')return <div className="onboarding-screen"><div className="onboarding-card"><GraduationCap size={36}/><h1>Setup sekolah sedang disediakan</h1><p>Pentadbir sekolah perlu melengkapkan pautan Drive dan import data murid dahulu.</p></div></div>;
 return <div className="onboarding-screen"><div className="onboarding-shell"><div className="wizard-brand"><ShieldCheck size={30}/><b>tegas</b><span>SETUP SEKOLAH</span></div><div className="wizard-account">{user.email||'Pemilik sekolah (demo)'}</div><h1>Sediakan ruang sekolah anda</h1><p>Satu sekolah, satu Drive, satu URL untuk pengguna sekolah.</p>{demo&&<div className="info"><AlertCircle size={18}/>Ini simulasi wizard GitHub Pages. Folder Drive sebenar tidak dicipta; data kekal dalam pelayar.</div>}<ol className="wizard-steps">{[[GraduationCap,'Sekolah'],[FolderCheck,'Drive'],[Upload,'Murid'],[Link,'URL sekolah']].map(([Icon,label],i)=><li key={label} className={step===i+1?'current':step>i+1?'done':''}><span>{step>i+1?<CheckCircle2 size={18}/>:<Icon size={18}/>}</span>{label}</li>)}</ol><section className="onboarding-card">{error&&<div className="error" role="alert">{error}</div>}
 {step===1&&<><span className="eyebrow">LANGKAH 1 / MAKLUMAT SEKOLAH</span><h2>Daftarkan sekolah anda</h2><p>Folder <b>tegas(KODSEKOLAH)</b> akan dicipta secara automatik dalam Drive akaun Google yang anda gunakan.</p><form onSubmit={e=>{e.preventDefault();run(saveProfile);}}><label>Kod sekolah<input required pattern="[A-Za-z0-9]{4,20}" maxLength={20} placeholder="Contoh: JBA5054" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>Nama sekolah<input required maxLength={1000} placeholder="Nama penuh sekolah" value={school} onChange={e=>setSchool(e.target.value)}/></label><label>Kod akses sekolah (4 angka)<input type="password" inputMode="numeric" autoComplete="new-password" required pattern="[0-9]{4}" minLength={4} maxLength={4} placeholder="Tetapkan kod akses" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><small>Kod ini diperlukan untuk masuk melalui URL sekolah. Kongsi dengan guru yang dibenarkan.</small><button className="primary" disabled={busy||folderBusy}>Simpan & cipta folder Drive <ArrowRight size={17}/></button></form></>}
 {step===2&&<><span className="eyebrow">LANGKAH 2 / FOLDER DRIVE</span><FolderCheck className="wizard-feature-icon" size={42}/><h2>{folderBusy?'Menyediakan folder sekolah…':'Sediakan folder sekolah'}</h2><p>Nama folder: <b>tegas({code})</b>. Murid, rekod kes, logo dan tetapan sekolah akan disimpan melalui backend dalam folder ini.</p>{!folderBusy&&<button className="primary" disabled={busy} onClick={()=>run(()=>perform(provision))}>Cuba cipta folder semula</button>}{!demo&&<a className="text-button reconnect-drive" href={'/auth/google?school='+encodeURIComponent(code)+'&reconnect=1'}>Benarkan semula akses Google Drive</a>}</>}
 {step===3&&<><span className="eyebrow">LANGKAH 3 / IMPORT DATA MURID</span><h2>Masukkan murid sekolah</h2><p>{demo?'Folder simulasi':'Folder Drive'}: <b>{data.onboarding.folderName||`tegas(${data.settings.code})`}</b></p><div className="wizard-roster"><UsersCount count={data.students.length}/></div><button className="secondary" onClick={onImport} disabled={busy}><Upload size={17}/>Upload Excel, CSV atau PDF</button>{demo&&!data.students.length&&<button className="text-button sample-button" onClick={()=>run(()=>perform(async()=>{await api('onboarding/sample',{});await onRefresh();}))}>Gunakan 3 murid rekaan untuk demo</button>}<p>Semak pratonton, kemudian pilih Sync atau Ganti semua sebelum mengesahkan import.</p><div className="wizard-actions"><button className="primary" disabled={busy||!data.students.length} onClick={()=>run(()=>perform(async()=>{const result=await api('onboarding/complete',{});setDoneUrl(result.schoolUrl);}))}>Selesai & dapatkan URL sekolah <ArrowRight size={17}/></button></div></>}
 {step===4&&<><CheckCircle2 className="wizard-feature-icon" size={46}/><span className="eyebrow">SETUP SELESAI</span><h2>Ruang sekolah anda tersedia</h2><p>{data.settings.school} · {data.settings.code}</p><label>URL sekolah<input readOnly value={doneUrl}/></label><div className="wizard-actions"><button className="secondary" onClick={()=>perform(async()=>{await navigator.clipboard.writeText(doneUrl);setCopied(true);})}><Copy size={16}/>{copied?'URL disalin':'Salin URL'}</button><button className="primary" onClick={()=>{window.location.href=doneUrl;window.location.reload();}}>Masuk ke sekolah <ArrowRight size={17}/></button></div><p>Kongsi URL sekolah dan kod akses dengan pengguna yang dibenarkan. Mereka masuk dengan kod 4 angka sahaja; identiti guru tidak direkodkan.</p>{demo&&<div className="info">URL demo ini menggunakan storan pelayar yang sama, bukan storan Drive bersama.</div>}</>}
 </section><small className="wizard-footer">TEGAS · Pengurusan disiplin & sahsiah sekolah</small></div></div>;
}
function UsersCount({count}){return <><strong>{count}</strong><span>murid dalam senarai sekolah</span></>;}
